{
  imports = [
    ./luasnip
    ./cmp.nix
    ./colorizer.nix
    ./comment.nix
    ./competitest.nix
    ./conform-nvim.nix
    ./fcitx5.nix
    ./friendly-snippets.nix
    ./guess-indent.nix
    ./illuminate.nix
    ./img-clip.nix
    ./indent-blankline.nix
    ./leap.nix
    ./lorem.nix
    ./lsp.nix
    ./lualine.nix
    ./mini.nix
    ./mkdnflow.nix
    ./neo-tree.nix
    # ./neorg.nix
    ./noice.nix
    ./notify.nix
    ./nvim-autopairs.nix
    ./precognition.nix
    ./substitute.nix
    ./telescope.nix
    ./treesitter.nix
    ./which-key.nix
    ./yazi.nix
  ];
}
